### ISSUE TITLE
Cleanup references of ubuntu 18.04.

### ISSUE THREAD

**Issue by wasup-yash** [kubernetes-sigs/image-builder#1198] opened 2023-06-17 13:50 UTC
**What steps did you take and what happened:**
The 1804 image has been deleted from `Ubuntu-os-cloud` project. 

**What did you expect to happen:**

referencing this https://github.com/kubernetes/kubernetes/issues/118718#issuecomment-1595711655

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi):

**Comment by AverageMarcus** [comment] 2023-06-19 17:47
@wasup-yash Can you confirm for me if this is:

* just related to the automated tests?
* only an issue for the GCE provider?
* applies to all providers?

If I understand correctly based on the linked issue, the problem is with the [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/scripts/ci-conformance.sh) periodic test failing. We can remove ubuntu-18.04 from image-builder but that wont stop the CAPG test from failing until they update their script.

I think that the ubuntu-18.04 base images are still available on other providers (e.g. the AMIs are still available on AWS) so removing all references to ubuntu-18.04 might not be appropriate without first consulting users on Slack etc.

**Comment by wasup-yash** [comment] 2023-06-19 18:07
> @wasup-yash Can you confirm for me if this is:
> 
> * just related to the automated tests?
> * only an issue for the GCE provider?
> * applies to all providers?
> 
> If I understand correctly based on the linked issue, the problem is with the [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/scripts/ci-conformance.sh) periodic test failing. We can remove ubuntu-18.04 from image-builder but that wont stop the CAPG test from failing until they update their script.
> 
> I think that the ubuntu-18.04 base images are still available on other providers (e.g. the AMIs are still available on AWS) so removing all references to ubuntu-18.04 might not be appropriate without first consulting users on Slack etc.

Yes you are right it will not be good to remove all references and as the Issue Mentioned it is related to the `Cluster-api-provider-gcp` so it will be good to remove it from the image-builder and as soon they update their script it will probably fix the issue.

**Comment by AverageMarcus** [comment] 2023-08-15 07:08
This has been done for GCP. We have https://github.com/kubernetes-sigs/image-builder/issues/1232 to cover removing Ubuntu 18.04 (and other EOL OSs) from other providers so I'm going to close this issues as done. 😄

**Closed by AverageMarcus** 2023-08-15 07:08 UTC
Labels: kind/cleanup
