### ISSUE TITLE
Build arm64 CAPI images

### ISSUE THREAD

**Issue by devigned** [kubernetes-sigs/image-builder#1067] opened 2023-01-30 21:28 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to build images for arm64 hardware. For example, [Azure arm64 machines](https://azure.microsoft.com/en-us/blog/azure-virtual-machines-with-ampere-altra-arm-based-processors-generally-available/) and [AWS arm64 machines](https://aws.amazon.com/ec2/instance-types/a1/).

**Describe the solution you'd like**
If supported on the infrastructure provider, be able to build arm64 CAPI images.

**Describe alternatives you've considered**
I don't know of any alternatives to this outside of building bespoke images.

/kind feature

**Comment by invidian** [comment] 2023-02-06 13:18
Duplicate of #936?

**Comment by ader1990** [comment] 2023-04-24 15:02
Hello, I have added here an example using QEMU-KVM on ARM64:
https://github.com/kubernetes-sigs/image-builder/pull/1142

**Comment by mboersma** [comment] 2023-07-17 16:54
/close

Duplicate of #936.

**Closed by mboersma** 2023-07-17 16:54 UTC
Labels: kind/feature
