### ISSUE TITLE
Image builder failing to download goss-linux-amd64

### ISSUE THREAD

**Issue by abhardwaj21-alyssum** [kubernetes-sigs/image-builder#1381] opened 2024-01-23 21:03 UTC
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

We are trying to setup EKS Anywhere on Nutanix following:
1. https://anywhere.eks.amazonaws.com/docs/getting-started/nutanix/nutanix-getstarted/
2. https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-nutanix-node-images
3. https://image-builder.sigs.k8s.io/capi/providers/nutanix.html#building-capi-images-for-nutanix-cloud-platform-ncp

While trying to create image for eksa nodes using following image-builder command and nutanix.json file we are facing following error:-

**COMMAND:-**

 image-builder build --os ubuntu --hypervisor nutanix --release-channel 1-26 --nutanix-config nutanix.json

**nutanix.json:-**

{
  "nutanix_cluster_name": "WUR",
  "source_image_name": "ubuntu-20.04",
  "image_name": "Ubuntu-22-eks",
  "image_export": "true",
  "nutanix_subnet_name": "AppVM-*****",
  "nutanix_endpoint": "10.yy.yy.yy",
  "nutanix_insecure": "true",
  "nutanix_port": "9440",
  "nutanix_username": "xyz",
  "nutanix_password": "**********",
  "http_proxy": "http://10.xx.xx.xx:8080/",
  "https_proxy": "http://10.xx.xx.xx:8080/",
  "extra_rpms": "wget",
  "extra_debs": "wget"
}

**Error Faced:-**

==> nutanix: Provisioning with Goss
==> nutanix: Configured to run on Linux
    nutanix: Creating directory: /tmp/goss
    nutanix: Installing Goss from, https://github.com/aelsabbahy/goss/releases/download/v0.3.16/goss-linux-amd64
    nutanix: Downloading Goss to /tmp/goss-0.3.16-linux-amd64
==> nutanix:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> nutanix:                                  Dload  Upload   Total   Spent    Left  Speed
==> nutanix:   0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
==> nutanix: curl: (28) Failed to connect to github.com port 443: Connection timed out
==> nutanix: --2024-01-22 20:30:15--  https://github.com/aelsabbahy/goss/releases/download/v0.3.16/goss-linux-amd64
==> nutanix: Resolving github.com (github.com)... 140.82.113.3
==> nutanix: Connecting to github.com (github.com)|140.82.113.3|:443... failed: Connection timed out.
==> nutanix: Retrying.

While when we tried to manually ssh to the image builder VM that got created as a result of the above command and explicitly export the https_proxy and http_proxy environment variables, the https://github.com/aelsabbahy/goss/releases/download/v0.3.16/goss-linux-amd64 got downloaded successfully. But from the image-builder command its failing.

**What did you expect to happen:**
image-builder should have got executed successfully creating and pushing the new image to the Nutanix Prism Images.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
 eksctl anywhere version- v0.18.3
 eksctl version- 0.167.0
 Python- 3.10.12
 ansible-core- 2.16.2

**Environment:** Dev

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi): nutanix

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Ubuntu 22.04.3 LTS
- Packer Version:  
- Packer Provider: Nutanix
- Ansible Version: ansible [core 2.16.2]
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`): Client Version: v1.29.0

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by AverageMarcus** [comment] 2024-01-25 18:20
Hi @abhardwaj21-alyssum, unfortunately we're not able to provide support for `eks-anywhere` as we're not associated with that project and wasn't even aware they made use of `image-builder` in this way until now.

If you are sure the issue is in `image-builder` itself, and are able to provide how to reproduce it using `image-builder` directly and not `eks-anywhere` we might be able to help but otherwise I suggest raising the issue with the `eks-anywhere` team.

If you'd like to discuss this with us, or if the `eks-anywhere` team does, you can reach out to us in the [#image-builder](https://kubernetes.slack.com/archives/C01E0Q35A8J) channel in the Kubernetes Slack.

I'm going to close this issue for now but if you're able to reproduce it with `image-builder` alone I'm more than happy to reopen it. 

/close

**Closed by AverageMarcus** 2024-01-25 18:20 UTC
Labels: kind/bug
